server:
  port: 3000
  base-url: /ggs_backups2025
db:
  port: 5433
  database: ggs2025_db
  password: PONER PASSSWORD
  user: ggs_backups2025_admin
install:
  dump:
    db:
      owner: ggs2025_owner
client-setup:
  lang: es
  title: GGS_BACKUPS2025
  background-img: ""
devel:
  delay: 0
log:
  db:
    on-demand: true
